[package]
name = "rinbot"
version = "0.1.0"
authors = ["Jared Boyd <boyd.jared95@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.8.6"